---
id: AWCFAF
name: Africa
areaConfigurations:
- areaCode: "ao"
  csvConfiguration:
    electoralListIds:
    - "AO001"
    - "AO002"
    - "AO003"
    - "AO004"
    - "AO005"
    - "AO006"
    - "AO007"
  elections:
    national:
      dates:
#       6: "2008-09-05/2008-09-06"
        6: "2008-09-06"
        7: "2012-08-31"
#       8: "2017-08-23/2017-08-26"
        8: "2017-08-23"
        9: "2022-08-24"
        10: "≤2027-08"
  translations:
    de: "Angola"
    en: "Angola"
    eo: "Angolo"
    fr: "Angola"
    nl: "Angola"
    no: "Angola"
- areaCode: "bi"
  elections:
    national:
      dates:
        7: "2005-07-04"
        8: "2010-07-23"
        9: "2015-06-29"
        10: "2020-05-20"
        11: "2025-06-05"
    presidential:
      dates:
        3: "2005-08-19"
        4: "2010-06-28"
        5: "2015-07-21"
        6: "2020-05-20"
        7: "≈2027-05"
  translations:
    de: "Burundi"
    en: "Burundi"
    eo: "Burundo"
    fr: "Burundi"
    nl: "Burundi"
    no: "Burundi"
- areaCode: "cd"
  elections:
    national:
      dates:
        8: "2006-07-30"
        9: "2011-11-28"
        10: "2018-12-30"
        11: "2023-12-20"
        12: "≤2028-12"
    presidential:
      dates:
        4: "2006-07-30"
        5: "2011-11-28"
        6: "2018-12-30"
        7: "2023-12-20"
        8: "≤2028-12"
  translations:
    de: "Demokratische Republik Kongo"
    en: "Democratic Republic of the Congo"
    eo: "Demokratia Respubliko Kongo"
    fr: "République démocratique du Congo"
    nl: "Democratische Republiek Congo"
    no: "Den demokratiske republikken Kongo"
- areaCode: "eg"
  elections:
    national:
      dates:
        25: "2000-10-18+2000-11-08"
        26: "2005-11-15+2005-11-26+2005-12-07"
        27: "2010-11-29"
        28: "2011-11-28+2012-01-11"
        29: "2015-10-17+2015-12-02"
#       30: "2020-10-24/2020-10-25+2020-11-07/2020-11-08"
        30: "2020-10-25+2020-11-08"
        31: "≤2025-10"
    presidential:
      dates:
        10: "2005-09-07"
#       11: "2012-05-23/2012-05-24+2012-06-16/2012-06-17"
        11: "2012-05-24+2012-06-17"
#       12: "2014-05-26/2014-05-27/2014-05-28"
        12: "2014-05-28"
#       13: "2018-03-26/2018-03-27/2018-03-28"
        13: "2018-03-28"
#       14: "2023-12-10/2023-12-11/2023-12-12"
        14: "2023-12-12"
        15: "≤2029-12"
  translations:
    de: "Ägypten"
    en: "Egypt"
    eo: "Egiptio"
    fr: "Égypt"
    nl: "Egypte"
    no: "Egypt"
- areaCode: "ga"
  elections:
    national:
      dates:
        12: "2001-12-09+2001-12-23"
#       13: "2006-12-17/2006-12-24"
        13: "2006-12-17"
        14: "2011-12-17"
        15: "2018-10-06+2018-10-27"
        16: "2023-08-26"
        17: "≈2025-08"
    presidential:
      dates:
        8: "2005-11-27"
        9: "2009-08-30"
        10: "2016-08-27"
        11: "2023-08-26"
        12: "≈2025-08"
  translations:
    de: "Gabun"
    en: "Gabon"
    eo: "Gabono"
    fr: "Gabon"
    nl: "Gabon"
    no: "Gabon"
- areaCode: "km"
  elections:
    national:
      dates:
        13: "2004-04-18+2004-04-25"
        14: "2009-12-06+2009-12-20"
        15: "2015-01-25+2015-02-22"
        16: "2020-01-19+2020-02-23"
        17: "2025-01-12+2025-02-16"
    presidential:
      dates:
        5: "2002-03-17+2002-04-14"
        6: "2006-04-16+2006-05-14"
        7: "2010-11-07+2010-12-26"
        8: "2016-02-21+2016-04-10"
        9: "2019-03-24"
        10: "2024-01-14"
        11: "≤2029-01"
  translations:
    de: "Komoren"
    en: "Comoros"
    eo: "Komoroj"
    fr: "Comores"
    nl: "Comoren"
    no: "Komorene"
- areaCode: "lr"
  elections:
    national:
      dates:
        51: "2005-10-11"
        52: "2011-10-11"
        53: "2014-12-20"
        54: "2017-10-10"
        55: "2020-12-08"
        56: "2023-10-10"
        57: "≤2029-10"
    presidential:
      dates:
        49: "2005-10-11+2005-11-08"
        50: "2011-10-11+2011-11-08"
        51: "2017-10-10+2017-12-26"
        52: "2023-10-10+2023-11-14"
        53: "≤2029-10"
  translations:
    de: "Liberia"
    en: "Liberia"
    eo: "Liberio"
    fr: "Liberia"
    nl: "Liberia"
    no: "Liberia"
- areaCode: "mg"
  elections:
    national:
      dates:
        13: "2002-12-15"
        14: "2007-09-23"
        15: "2013-12-20"
        16: "2019-05-27"
        17: "2024-05-29"
        18: "≤2029-05"
    presidential:
      dates:
        7: "2001-12-16"
        8: "2006-12-03"
        9: "2013-10-25+2013-12-20"
        10: "2018-11-07+2018-12-19"
        11: "2023-11-16"
        12: "≤2028-11"
  translations:
    de: "Madagaskar"
    en: "Madagascar"
    eo: "Madagaskaro"
    fr: "Madagascar"
    nl: "Madagaskar"
    no: "Madagaskar"
- areaCode: "ml"
  elections:
    national:
      dates:
        14: "2002-07-14"
        15: "2007-07-01+2007-07-22"
        16: "2013-11-24+2013-12-15"
        17: "2020-03-28+2020-04-19"
        18: "2025"
    presidential:
      dates:
        5: "2002-04-28+2002-05-12"
        6: "2007-04-29"
        7: "2013-07-28+2013-08-11"
        8: "2018-07-29+2018-08-12"
        9: "2025"
  translations:
    de: "Mali"
    en: "Mali"
    eo: "Malio"
    fr: "Mali"
    nl: "Mali"
    no: "Mali"
- areaCode: "mr"
  elections:
    national:
      dates:
        6: "2001-10-19+2001-10-26"
        7: "2006-11-19+2006-12-03"
        8: "2013-11-23+2013-12-21"
        9: "2018-09-01+2018-09-15"
        10: "2023-05-13+2023-05-27"
        11: "≤2028-05"
    presidential:
      dates:
        7: "2003-11-07"
        8: "2007-03-11+2007-03-25"
        9: "2009-07-18"
        10: "2014-06-21"
        11: "2019-06-22"
        12: "2024-06-29"
        13: "≈2029-06"
  translations:
    de: "Mauretanien"
    en: "Mauritania"
    eo: "Maŭritanio"
    fr: "Mauritanie"
    nl: "Mauritanië"
    no: "Mauritania"
- areaCode: "sl"
  elections:
    national:
      dates:
        15: "2002-05-14"
        16: "2007-08-11"
        17: "2012-11-17"
        18: "2018-03-07"
        19: "2023-06-24"
        20: "≤2028-06"
    presidential:
      dates:
        3: "2002-05-14"
        4: "2007-08-11+2007-09-08"
        5: "2012-11-17"
        6: "2018-03-07+2018-03-31"
        7: "2023-06-24"
        8: "≤2028-06"
  translations:
    de: "Sierra Leone"
    en: "Sierra Leone"
    eo: "Sieraleono"
    fr: "Sierra Leone"
    nl: "Sierra Leone"
    no: "Sierra Leone"
- areaCode: "td"
  elections:
    national:
      dates:
        10: "2002-04-21"
        11: "2011-02-13"
        12: "2024-12-29"
        13: "≤2028-12"
    presidential:
      dates:
        3: "2001-05-20"
        4: "2006-05-03"
        5: "2011-04-25"
        6: "2016-04-10"
        7: "2021-04-11"
        8: "2024-05-06"
        9: "≤2029-05"
  translations:
    de: "Tschad"
    en: "Chad"
    eo: "Ĉado"
    fr: "Tchad"
    nl: "Tsjaad"
    no: "Tsjad"
- areaCode: "za"
  csvConfiguration:
    electoralListIds:
    - "ZA001"
    - "ZA002"
    - "ZA003"
    - "ZA004"
    - "ZA005"
    - "ZA006"
    - "ZA007"
    - "ZA008"
    - "ZA009"
    - "ZA010"
    - "ZA011"
  elections:
    national:
      dates:
        24: "2004-04-14"
        25: "2009-04-22"
        26: "2014-05-07"
        27: "2019-05-08"
        28: "2024-05-29"
        29: "≤2029-05"
  translations:
    de: "Südafrika"
    en: "South Africa"
    eo: "Sud-Afriko"
    fr: "Afrique du Sud"
    nl: "Zuid-Afrika"
    no: "Sør-Afrika"
- areaCode: "zw"
  elections:
    national:
      dates:
#       27: "2000-06-24/2000-06-25"
        27: "2000-06-25"
        28: "2005-03-31"
        29: "2008-03-29"
        30: "2013-07-31"
        31: "2018-07-30"
        32: "2023-08-23"
        33: "≤2028-08"
    presidential:
      dates:
#       3: "2002-03-09/2002-03-10/2002-03-11"
        3: "2002-03-11"
        4: "2008-03-29+2008-06-27"
        5: "2013-07-31"
        6: "2018-07-30"
        7: "2023-08-23"
        8: "≤2028-08"
  translations:
    de: "Simbabwe"
    en: "Zimbabwe"
    eo: "Zimbabvo"
    fr: "Zimbabwe"
    nl: "Zimbabwe"
    no: "Zimbabwe"
widgetsConfiguration:
  tableFontFamily: "Alegreya Sans,'Helvetica Neue',Helvetica,sans-serif"
  tableStylesheets:
  - https://fonts.googleapis.com/css?family=Alegreya+Sans%3A400%2C700%2C400italic%2C700italic%2C600%2C600italic%7CAlegreya+Sans%3A400%2C500%2C600%2C700%2C400italic%2C700italic&ver=1
  - https://europeelects.eu/wp-content/themes/chaplin/style.css?ver=2.6.7
