---
areaConfigurations:
- areaCode: "ao"
  csvConfiguration:
    electoralListIds:
    - "AO001"
    - "AO002"
    - "AO003"
    - "AO004"
    - "AO005"
    - "AO006"
    - "AO007"
  elections:
    national:
      dates:
#       6: "2008-09-05/2008-09-06"
        6: "2008-09-06"
        7: "2012-08-31"
#       8: "2017-08-23/2017-08-26"
        8: "2017-08-23"
        9: "2022-08-24"
        10: "≤2027-08"
  translations:
    de: "Angola"
    en: "Angola"
    eo: "Angolo"
    fr: "Angola"
    nl: "Angola"
    no: "Angola"
- areaCode: "ga"
  elections:
    national:
      dates:
        12: "2001-12-09+2001-12-23"
#       13: "2006-12-17/2006-12-24"
        13: "2006-12-17"
        14: "2011-12-17"
        15: "2018-10-06+2018-10-27"
        16: "2023-08-26"
    presidential:
      dates:
        8: "2005-11-27"
        9: "2009-08-30"
        10: "2016-08-27"
        11: "2023-08-26"
  translations:
    de: "Gabun"
    en: "Gabon"
    eo: "Gabono"
    fr: "Gabon"
    nl: "Gabon"
    no: "Gabon"
- areaCode: "mr"
  elections:
    national:
      dates:
        6: "2001-10-19+2001-10-26"
        7: "2006-11-19+2006-12-03"
        8: "2013-11-23+2013-12-21"
        9: "2018-09-01+2018-09-15"
        10: "2023-05-13+2023-05-27"
    presidential:
      dates:
        7: "2003-11-07"
        8: "2007-03-11+2007-03-25"
        9: "2009-07-18"
        10: "2014-06-21"
        11: "2019-06-22"
        12: "≈2024-06"
  translations:
    de: "Mauretanien"
    en: "Mauritania"
    eo: "Maŭritanio"
    fr: "Mauritanie"
    nl: "Mauritanië"
    no: "Mauritania"
- areaCode: "lr"
  elections:
    national:
      dates:
        51: "2005-10-11"
        52: "2011-10-11"
        53: "2014-12-20"
        54: "2017-10-10"
        55: "2020-12-08"
        56: "2023-10-10"
    presidential:
      dates:
        49: "2005-10-11+2005-11-08"
        50: "2011-10-11+2011-11-08"
        51: "2017-10-10+2017-12-26"
        52: "2023-10-10"
  translations:
    de: "Liberia"
    en: "Liberia"
    eo: "Liberio"
    fr: "Liberia"
    nl: "Liberia"
    no: "Liberia"
- areaCode: "sl"
  elections:
    national:
      dates:
        15: "2002-05-14"
        16: "2007-08-11"
        17: "2012-11-17"
        18: "2018-03-07"
        19: "2023-06-24"
    presidential:
      dates:
        3: "2002-05-14"
        4: "2007-08-11+2007-09-08"
        5: "2012-11-17"
        6: "2018-03-07+2018-03-31"
        7: "2023-06-24"
  translations:
    de: "Sierra Leone"
    en: "Sierra Leone"
    eo: "Sieraleono"
    fr: "Sierra Leone"
    nl: "Sierra Leone"
    no: "Sierra Leone"
- areaCode: "za"
  csvConfiguration:
    electoralListIds:
    - "ZA001"
    - "ZA002"
    - "ZA003"
    - "ZA004"
    - "ZA005"
    - "ZA006"
    - "ZA007"
  elections:
    national:
      dates:
        24: "2004-04-14"
        25: "2009-04-22"
        26: "2014-05-07"
        27: "2019-05-08"
        28: "≤2024-05"
  translations:
    de: "Südafrika"
    en: "South Africa"
    eo: "Sud-Afriko"
    fr: "Afrique du Sud"
    nl: "Zuid-Afrika"
    no: "Sør-Afrika"
- areaCode: "zw"
  elections:
    national:
      dates:
#       27: "2000-06-24/2000-06-25"
        27: "2000-06-25"
        28: "2005-03-31"
        29: "2008-03-29"
        30: "2013-07-31"
        31: "2018-07-30"
        32: "2023-08-23"
    presidential:
      dates:
#       3: "2002-03-09/2002-03-10/2002-03-11"
        3: "2002-03-11"
        4: "2008-03-29+2008-06-27"
        5: "2013-07-31"
        6: "2018-07-30"
        7: "2023-08-23"
  translations:
    de: "Simbabwe"
    en: "Zimbabwe"
    eo: "Zimbabvo"
    fr: "Zimbabwe"
    nl: "Zimbabwe"
    no: "Zimbabwe"
