---
areaConfigurations:
- areaCode: "mr"
  elections:
    national:
      dates:
        6: "2001-10-19+2001-10-26"
        7: "2006-11-19+2006-12-03"
        8: "2013-11-23+2013-12-21"
        9: "2018-09-01+2018-09-15"
        10: "2023-05-13+2023-05-27"
    president:
      dates:
        7: "2003-11-07"
        8: "2007-03-11+2007-03-25"
        9: "2009-07-18"
        10: "2014-06-21"
        11: "2019-06-22"
        12: "≈2024-06"
  translations:
    de: "Mauretanien"
    en: "Mauritania"
    eo: "Maŭritanio"
    fr: "Mauritanie"
    nl: "Mauritanië"
    no: "Mauritania"
- areaCode: "za"
  csvConfiguration:
    electoralListIds:
    - "ZA001"
    - "ZA002"
    - "ZA003"
    - "ZA004"
    - "ZA005"
    - "ZA006"
    - "ZA007"
  elections:
    national:
      dates:
        24: "2004-04-14"
        25: "2009-04-22"
        26: "2014-05-07"
        27: "2019-05-08"
        28: "≤2024-05"
  translations:
    de: "Südafrika"
    en: "South Africa"
    eo: "Sud-Afriko"
    fr: "Afrique du Sud"
    nl: "Zuid-Afrika"
    no: "Sør-Afrika"
